# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Annie
tagline:          annie's blog
description:      learning notes
url:              https://joe-annie.github.io/
baseurl:          /

author:
  name:           'Annie Zheng'
  url:            https://joe-annie.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Joe-annie/joe-annie.github.io
